etc/install: small fix to error messages for missing programs

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -13,16 +13,16 @@ cat <<EOF
 EOF
 
 # Check minimal dependencies
-if ! command -v git &> /dev/null; then echo "ERROR: git not found. (Try $APT install git)"; exit; fi
-if ! command -v curl &> /dev/null; then echo "ERROR: curl not found. (Try $APT install curl)"; exit; fi
-if ! command -v wget &> /dev/null; then echo "ERROR: wget not found. (Try $APT install wget)"; exit; fi
+if ! command -v git  &> /dev/null; then echo "ERROR: git not found. (Try: brew/apt install git)"; exit 1; fi
+if ! command -v curl &> /dev/null; then echo "ERROR: curl not found. (Try: brew/apt install curl)"; exit 1; fi
+if ! command -v wget &> /dev/null; then echo "ERROR: wget not found. (Try: brew/apt install wget)"; exit 1; fi
 
 if which python3 > /dev/null; then
     PYTHON="python3"
 else
     PYTHON="python"
 fi
-if ! command -v $PYTHON &> /dev/null; then echo "ERROR: python not found. (Try $APT install python3-pip)"; exit; fi
+if ! command -v $PYTHON &> /dev/null; then echo "ERROR: python3 not found. (Try: apt install python3-pip)"; exit 1; fi
 
 _version_check() {
     curver="$1"; targetver="$2";
