zsh: Make a warning if the terminfo is not available.

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -199,6 +199,10 @@ fi
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
 
+# If terminfo is missing on a remote machine, give a warning
+if ! infocmp $TERM > /dev/null; then
+  echo -e '\033[0;33m'"terminfo for TERM = $TERM is missing. Run ~/.dotfiles/etc/terminfo.sh"'\033[0m'
+fi
 
 # iTerm integration (for OS X iTerm2)
 # @see https://iterm2.com/shell_integration.html
